<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="login.login_test-20180424174303" tests="1" time="1.038">
	<testcase classname="login.login_test" name="test_01_login" time="1.038">
		<error message="Message: Tried to run command without establishing a connection
" type="WebDriverException">
<![CDATA[Traceback (most recent call last):
  File "/home/rishabh/docs-screenshot/webui/tests/login.py", line 73, in test_01_login
    self.screenshot("-e")
  File "/home/rishabh/docs-screenshot/webui/tests/login.py", line 98, in screenshot
    driver.save_screenshot(cwd + "/screenshot/"  + "screenshot-" + final_file + "-" + test_method_name + ".png")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 931, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 908, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 940, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 950, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: Tried to run command without establishing a connection

]]>		</error>
	</testcase>
	<system-out>
<![CDATA[loging in FreeNAS new webui- woot woot
Taking screenshot for login-test_01_login
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
