<?xml version="1.0" ?>
<testsuite errors="3" failures="0" name="acc_user.create_user_test-20180424174805" tests="3" time="185.510">
	<testcase classname="acc_user.create_user_test" name="test_01_nav_acc_user" time="91.209">
		<error message="Test fail: Please check the traceback" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/rishabh/docs-screenshot/webui/tests/acc_user.py", line 82, in test_01_nav_acc_user
    self.assertEqual("Just for fail", str(Exception), msg="Test fail: Please check the traceback")
AssertionError: Test fail: Please check the traceback
]]>		</error>
	</testcase>
	<testcase classname="acc_user.create_user_test" name="test_02_create_newuser" time="63.177">
		<error message="Test fail: Please check the traceback" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/rishabh/docs-screenshot/webui/tests/acc_user.py", line 107, in test_02_create_newuser
    self.assertEqual("Just for fail", str(Exception), msg="Test fail: Please check the traceback")
AssertionError: Test fail: Please check the traceback
]]>		</error>
	</testcase>
	<testcase classname="acc_user.create_user_test" name="test_03_close_navAccount" time="31.124">
		<error message="Test fail: Please check the traceback" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/rishabh/docs-screenshot/webui/tests/acc_user.py", line 119, in test_03_close_navAccount
    self.assertEqual("Just for fail", str(Exception), msg="Test fail: Please check the traceback")
AssertionError: Test fail: Please check the traceback
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[ navigating to the user submenu
Taking screenshot for acc_user-test_01_nav_acc_user
  File "/home/rishabh/docs-screenshot/webui/tests/acc_user.py", line 63, in test_01_nav_acc_user
    a = driver.find_element_by_xpath(xpaths['navAccount'])

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 365, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 855, in find_element
    'value': value})['value']

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)

NoSuchElementException: Message: Unable to locate element: //*[@id="nav-1"]/div/a[1]


 creating a new user with create new primary group
Taking screenshot for acc_user-test_02_create_newuser
  File "/home/rishabh/docs-screenshot/webui/tests/acc_user.py", line 95, in test_02_create_newuser
    hover_element = driver.find_element_by_xpath(xpaths['fabTrigger'])

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 365, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 855, in find_element
    'value': value})['value']

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)

NoSuchElementException: Message: Unable to locate element: //*[@id="myFab"]/div/smd-fab-trigger/button


 closing account menu
Taking screenshot for acc_user-test_03_close_navAccount
  File "/home/rishabh/docs-screenshot/webui/tests/acc_user.py", line 111, in test_03_close_navAccount
    driver.find_element_by_xpath(xpaths['navAccount']).click()

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 365, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 855, in find_element
    'value': value})['value']

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)

NoSuchElementException: Message: Unable to locate element: //*[@id="nav-1"]/div/a[1]


]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
