<?xml version="1.0" ?>
<testsuite errors="2" failures="0" name="sys_update.check_update_test-20180424181648" tests="2" time="62.244">
	<testcase classname="sys_update.check_update_test" name="test_01_nav_sys_update" time="31.130">
		<error message="Test fail: Please check the traceback" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/rishabh/docs-screenshot/webui/tests/sys_update.py", line 72, in test_01_nav_sys_update
    self.assertEqual("Just for fail", str(Exception), msg="Test fail: Please check the traceback")
AssertionError: Test fail: Please check the traceback
]]>		</error>
	</testcase>
	<testcase classname="sys_update.check_update_test" name="test_02_check_update_now" time="31.114">
		<error message="Test fail: Please check the traceback" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/rishabh/docs-screenshot/webui/tests/sys_update.py", line 114, in test_02_check_update_now
    self.assertEqual("Just for fail", str(Exception), msg="Test fail: Please check the traceback")
AssertionError: Test fail: Please check the traceback
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[Taking screenshot for sys_update-test_01_nav_sys_update
  File "/home/rishabh/docs-screenshot/webui/tests/sys_update.py", line 48, in test_01_nav_sys_update
    a = driver.find_element_by_xpath(xpaths['navSystem'])

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 365, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 855, in find_element
    'value': value})['value']

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)

NoSuchElementException: Message: Unable to locate element: //*[@id='nav-2']/div/a[1]


Taking screenshot for sys_update-test_02_check_update_now
  File "/home/rishabh/docs-screenshot/webui/tests/sys_update.py", line 77, in test_02_check_update_now
    driver.find_element_by_xpath(xpaths['buttonChecknow']).click()

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 365, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 855, in find_element
    'value': value})['value']

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)

  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)

NoSuchElementException: Message: Unable to locate element: /html/body/app-root/app-admin-layout/mat-sidenav-container/mat-sidenav-content/div/app-update/mat-card/div/div[3]/div/button[1]


]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
